{
  "sksl": {
    "entrypoint": "lab4_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec4 uTargetColor;\nuniform float uConstraintsLength;\nuniform vec3 uConstraints[10];\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord();\n    for (int i = 0; i < 10; i++)\n    {\n        if (float(i) == uConstraintsLength)\n        {\n            break;\n        }\n        if (!(((uConstraints[i].x * uv.x) + (uConstraints[i].y * uv.y)) <= uConstraints[i].z))\n        {\n            fragColor = vec4(0.0);\n            return;\n        }\n    }\n    fragColor = uTargetColor;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTargetColor",
        "rows": 4,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uConstraintsLength",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 10,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uConstraints",
        "rows": 3,
        "type": 10
      }
    ]
  }
}